version: '3.3'

services:
  streamlit-app:
    image: python:3.10
    command: bash -c " cd sar/ && pip install -r requirements.txt  && streamlit run web.py"
    volumes:
      - ../Youtube_Data_Extraction_and_Visualization:/sar
    ports:
      - "8501:8501"
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
