config:
    #Enter Your Google API Key here
    Google_API_Key: ""

    #Enter Your MongoDB URL here
    MongoDB_URL: "mongodb+srv://saravana:Saravana22@cluster0.fcz359j.mongodb.net/?retryWrites=true&w=majority"